name: Deploy Frame Extraction Service to GCP

env:
  FULL_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo-wade-1/frame-extraction-service
on:
  push:
    branches:
      - frame-extraction-service
      - main
    paths:
      - 'frame-extraction-service/**'
      - '.github/workflows/deploy-frame-extraction-service.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
        
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build the Docker image
        run: |
          cd frame-extraction-service
          docker build -t $FULL_IMAGE_NAME .
          docker push $FULL_IMAGE_NAME

      - name: Deploy the Docker image to Cloud Run
        run: |
          gcloud run deploy frame-extraction-service \
            --image $FULL_IMAGE_NAME \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
            