name: Deploy Frame Extraction Service to GCP

env:
  FULL_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repo-wade-1/frame-extraction-service

on:
  push:
    branches:
      - frame-extraction-service
      - main
    paths:
      - 'frame-extraction-service/**'
      - '.github/workflows/deploy-frame-extraction-service.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker to use GCP Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          cd frame-extraction-service
          docker buildx build --cache-from=type=registry,ref=$FULL_IMAGE_NAME \
                              --cache-to=type=inline \
                              -t $FULL_IMAGE_NAME . \
                              --push

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frame-extraction-service \
            --image $FULL_IMAGE_NAME \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
